### ISSUE TITLE
go get github.com/ServiceComb/go-chassis report undefined: restful.SetCacheReadEntity error

### ISSUE THREAD

**Issue by lexkong** [ServiceComb/go-chassis#105]
[root@aliyun workspace]#go get github.com/ServiceComb/go-chassis
\# github.com/ServiceComb/go-chassis/server/restful
mygo/src/github.com/ServiceComb/go-chassis/server/restful/restful_server.go:34: undefined: restful.SetCacheReadEntity

i guess go-chassis may do some basic testing, but it not, I doubt if this is an official Huawei open source project

**Comment by tianxiaoliang** [comment]
it doesn't support "go get" as we mentioned installation in this section "https://go.huaweicse.com/gai-shu/an-zhuang-ben-di-kai-fa-huan-jing/install.html", plz refer to it

**Comment by zenlinTechnofreak** [comment]
Hi Shawn , why go-chassis donot suspport ‘go get’, anyway ,it is the
inertial and regular way in Go world.
Hi Qilin , can you help to maintain this.

2018-03-26 17:22 GMT+08:00 Shawn <notifications@github.com>:

**Comment by tianxiaoliang** [comment]
Some deps We can not control their API change, one practice is fork all of deps and change go-chassis imports. that cost a lot of operation, but solve the problem forever

 for example go-restful changed API after we import the latest code of it. which means we have to continuously follow latest deps codes. even we do that. another problem is some day the old release of go chassis can not use "go get"

**Comment by tianxiaoliang** [comment]
https://github.com/ServiceComb/go-chassis/pull/195 fixed
