### ISSUE TITLE
route-rule fails for darklaunch if we don't give weight.

### ISSUE THREAD

**Issue by savitaashture** [ServiceComb/go-chassis#145]
Configuration is 
```
{
  "policyType": "RULE",
  "ruleItems": [
    {
      "groupName": "s2",
      "groupCondition": "version=0.0.1",
      "policyCondition": "test=40"
    },
    {
      "groupName": "s1",
      "groupCondition": "version=0.4",
      "policyCondition": "test!=40"
    }
  ]
}
```
Root Cause:

https://github.com/ServiceComb/go-chassis/blob/master/core/router/router_config.go#L64
In 
validateRule(rules map[string][]*model.RouteRule) bool
function if we don't provide weight by default it will take 100% so as per the above configuration first time weight become 100 and in the second iteration it becomes 200
https://github.com/ServiceComb/go-chassis/blob/master/core/router/router_config.go#L74
Because of this condition validateRule function returns false.
So the version will be allways **latest** and not the one which has been given in the configuration like 
**0.0.1** or **0.4**

**Comment by tianxiaoliang** [comment]
thanks very much
