### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by cs2mw** [ServiceComb/go-chassis#184]
C:\devtools\java>go get -u github.com/ServiceComb/go-chassis
# github.com/ServiceComb/go-chassis/core/lager
C:\cs2mw\workspace\go\src\github.com\ServiceComb\go-chassis\core\lager\lager.go:11:2: log redeclared as imported package name
        previous declaration at C:\cs2mw\workspace\go\src\github.com\ServiceComb\go-chassis\core\lager\lager.go:4:2
C:\cs2mw\workspace\go\src\github.com\ServiceComb\go-chassis\core\lager\lager.go:54:2: undefined: "github.com/ServiceComb/paas-lager".Println
C:\cs2mw\workspace\go\src\github.com\ServiceComb\go-chassis\core\lager\lager.go:75:2: undefined: stlager
C:\cs2mw\workspace\go\src\github.com\ServiceComb\go-chassis\core\lager\lager.go:82:12: undefined: stlager
C:\cs2mw\workspace\go\src\github.com\ServiceComb\go-chassis\core\lager\lager.go:97:3: undefined: "github.com/ServiceComb/paas-lager".Println
C:\cs2mw\workspace\go\src\github.com\ServiceComb\go-chassis\core\lager\lager.go:100:3: undefined: "github.com/ServiceComb/paas-lager".Printf

**Comment by tianxiaoliang** [comment]
Sorry we didn't support go get 
http://go-chassis.readthedocs.io/en/latest/getstarted/install.html

**Comment by cs2mw** [comment]
thx，it's ok according to docs above.
