### ISSUE TITLE
Register your Schema to go-chassis

### ISSUE THREAD

**Issue by Victoryship** [ServiceComb/go-chassis#191]
where should i register？这个注册接口应该在哪里注册？

**Comment by tianxiaoliang** [comment]
there is a pkg "chassis", and it has exposed Register method, will this answer helps you?

**Comment by tianxiaoliang** [comment]
chassis.RegisterSchema("rest", &HelloServer{},server.WithSchemaID("HelloServer"))

besides there is complete examples is exsamples folder

**Comment by Victoryship** [comment]
thank you!
