### ISSUE TITLE
How do I know if the framework started

### ISSUE THREAD

**Issue by Victoryship** [ServiceComb/go-chassis#193]
I wrote the example of communication, but I don't know if it started go-chassis. Because my service center has always been empty. According to the example, what uri to visit is to check it.

我模仿communication例子写的，但我不知道是否启动了go-chassis。因为我的service center 一直是空的。请问按照例子写的是该访问哪个uri查看呢。

![image](https://user-images.githubusercontent.com/19524632/39663846-d2afe95c-50ac-11e8-8bd4-94dca5c4ca12.png)

![image](https://user-images.githubusercontent.com/19524632/39663858-f79dca90-50ac-11e8-9088-349f17a7be97.png)

![image](https://user-images.githubusercontent.com/19524632/39663852-e2520052-50ac-11e8-8a86-83ae80d5823c.png)

![image](https://user-images.githubusercontent.com/19524632/39663880-55fbc7b8-50ad-11e8-9484-365ce47fc0dd.png)

**Comment by tianxiaoliang** [comment]
you can start with 
https://github.com/ServiceComb/go-chassis/tree/master/examples/rest
and
https://github.com/ServiceComb/go-chassis/tree/master/examples/rpc 

above includes 2 simple examples with service center

communication is the examples of simple e2e demo without service center

**Comment by Victoryship** [comment]
Then execute go run to run the mian.go file in server and client

**Comment by tianxiaoliang** [comment]
if you use go run instead of build and run binary, you must export CHASSIS_HOME=/path/to/your/work/folder

**Comment by Victoryship** [comment]
thanks then i am get a error

![image](https://user-images.githubusercontent.com/19524632/39684676-1ed9d24a-51f0-11e8-8928-3f9a4ed4731c.png)

**Comment by Victoryship** [comment]
and another error 
![image](https://user-images.githubusercontent.com/19524632/39685592-47d74e24-51f6-11e8-9f72-b1352842c9c5.png)

**Comment by tianxiaoliang** [comment]
plz follow the right installation

**Comment by tianxiaoliang** [comment]
http://go-chassis.readthedocs.io/en/latest/getstarted/install.html

**Comment by tianxiaoliang** [comment]
@Victoryship  did this solve your problem

**Comment by Victoryship** [comment]
thank you!!! There are too many packages not installed。go get -u github.com/FiloSottile/gvt and gvt restore solve this question. thank you !!!
