### ISSUE TITLE
c client and two-way communication

### ISSUE THREAD

**Issue by wuhenfeike** [ServiceComb/go-chassis#203]
if i want write c/c++ client connect to servicecomb and can two-way communication between c/c++ client and server， what should I do？

**Comment by tianxiaoliang** [comment]
go-chassis support http protocol just check the examples/rest

**Comment by wuhenfeike** [comment]
@tianxiaoliang i could client access to server， but， what should I do when server access to client？ thanks！

**Comment by tianxiaoliang** [comment]
plz use cse mesher to reach this
https://support.huaweicloud.com/devg-cse/cse_mesh_0002.html
it is not open source but it can cooperate with go-chassis in same eco system. it is also free to use 
just deploy your  c program with mesher

**Comment by tianxiaoliang** [comment]
guess you understand chinese
http://servicecomb.incubator.apache.org/assets/slides/20171209/PracticeOfServiceMeshOnHuaweiPublicCloud.pdf
