### ISSUE TITLE
glide install error

### ISSUE THREAD

**Issue by liwei5** [ServiceComb/go-chassis#231]
glide install in go-chassis dir:
```bash
[INFO]	--> Fetching updates for github.com/kr/logfmt
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
```
![image](https://user-images.githubusercontent.com/1586298/41402861-faaee6fc-6ff5-11e8-8405-4f684a221a95.png)

**Comment by tianxiaoliang** [comment]
zipkin introduced this repo and I have tried in my laptop, I can surely download all the repos
