### ISSUE TITLE
Constraints on microservice version

### ISSUE THREAD

**Issue by crystaldust** [ServiceComb/go-chassis#244]
Hi, I find that the `version` field defined in conf/microservice.yaml is restricted to be in the format  `^[0-9]+(\\.[0-9]+){0,2}$}`, while under some environment like kubernetes, the version is usually a label and can be defined with any character. So why does chassis have the constraint? Is it possible that we take version as a common string(like `v1`, `v2` or anything) for flexibility?

**Comment by tianxiaoliang** [comment]
go chassis can run with Istio now， it will not constraint your version label，you don't need to define in microservice.yaml also, instead just define in k8s deployment

Running with sc constraints version to follow semantic version,we will consider to support free usage of version

**Comment by crystaldust** [comment]
Cool, happy to hear that!
