### ISSUE TITLE
服务心跳失败重注册的时候实例ID有变化，是否合理？

### ISSUE THREAD

**Issue by zhangfeng751** [ServiceComb/go-chassis#252]
服务心跳失败重注册的时候实例ID有变化，是否合理？
![image](https://user-images.githubusercontent.com/17715446/42172466-9c002d5c-7e4e-11e8-800f-74d4eda601b5.png)
java-chassis重注册，实例ID不变

**Comment by z00194267** [comment]
java-chassis心跳丢失重注册时是带着instanceId注册的，go-chassis没有，不带id重注册，sc会重新生成实例ID  @tianxiaoliang

**Comment by tianxiaoliang** [comment]
make send ,thank u for advice

**Comment by tianxiaoliang** [comment]
fixed, thanks again, keep coming
