### ISSUE TITLE
Prepare CI env with Travis

### ISSUE THREAD

**Issue by asifdxtreme** [ServiceComb/go-chassis#3]

**Comment by wangkirin** [comment]
I think we can list what we have/havn't done here
- [x] go build 
- [x] go fmt
- [x] deadcode 
- [ ] govet
- [ ] UnitTest
- [ ] goconst
- [ ] misspell
- [ ] gocyclo

**Comment by wangkirin** [comment]
thanks to the PR of @thandayuthapani   #11 
we have finish `goconst` and  `misspell` now

**Comment by asifdxtreme** [comment]
@wangkirin @tianxiaoliang  we need to decide on gocyclo range, what should be the maximum cyclomatic complexities allowed ranging from 10 to 20.

**Comment by wangkirin** [comment]
@asifdxtreme in our daily work, the maximum cyclomatic must below 50 and average cyclomatic must below 15 , may be in go-chassis 20 is ok
