### ISSUE TITLE
go get -u github.com/ServiceComb/go-chassis failed

### ISSUE THREAD

**Issue by 728443778** [ServiceComb/go-chassis#30]
when use go get -u github.com/ServiceComb/go-chassis this response is 

package github.com/openzipkin/zipkin-go-opentracing/_thrift/gen-go/zipkincore: cannot find package "github.com/openzipkin/zipkin-go-opentracing/_thrift/gen-go/zipkincore" in any of:
	/usr/local/go/src/github.com/openzipkin/zipkin-go-opentracing/_thrift/gen-go/zipkincore (from $GOROOT)
	/home/chenghua/go/src/github.com/openzipkin/zipkin-go-opentracing/_thrift/gen-go/zipkincore (from $GOPATH)

**Comment by tianxiaoliang** [comment]
I found this problem today too, we will invetigate on this, and you can use
git clone and gvt restore to use this repo first, sorry.  that is the way
we use

2018-01-29 11:14 GMT+08:00 风的季节 <notifications@github.com>:

**Comment by 728443778** [comment]
Yes, I already ran the example.
