### ISSUE TITLE
Is there any plan to support Ctrip apollo configuration server ?

### ISSUE THREAD

**Issue by liwei5** [ServiceComb/go-chassis#40]
Is there any plan to support Ctrip apollo configuration server ? Just like java-chassis.
![f74de300-3ff5-47bf-baaf-acf32a6e34d1](https://user-images.githubusercontent.com/1586298/35542501-496089a6-059b-11e8-9360-b2955799bbfe.png)

**Comment by liwei5** [comment]
here is go client for apollo :  https://github.com/zouyx/agollo

**Comment by tianxiaoliang** [comment]
Yes, we do, are you planning to use go-chassis?

**Comment by liwei5** [comment]
@tianxiaoliang  
Yes, Golang and Java are the main programming languages for my team.
Servicecomb supports golang and Java, and draws on the idea of spring cloud which is why I'm attracted to it. I want to use it as a microservices framework alternative. Currently concerned about its functional integrity, stability.

**Comment by tianxiaoliang** [comment]
https://github.com/ServiceComb/go-chassis/wiki/Road-Map
Here is our roadmap I have made this feature on list

**Comment by tianxiaoliang** [comment]
https://github.com/ServiceComb/go-chassis/releases/tag/v0.6 
@liwei5  the latest release 0.6 support ctrip apollo now
