### ISSUE TITLE
can't go get

### ISSUE THREAD

**Issue by willxm** [ServiceComb/go-chassis#41]
```
$ go get github.com/ServiceComb/go-chassis
# github.com/ServiceComb/go-chassis/server/restful
../github.com/ServiceComb/go-chassis/server/restful/restful_server.go:34:2: undefined: restful.SetCacheReadEntity
```

**Comment by tianxiaoliang** [comment]
we will invetigate on this,  sorry about this experience.   you can use
git clone and gvt restore to use this repo first ,that is the way we use for now

**Comment by tianxiaoliang** [comment]
I changed doc https://go.huaweicse.cn/gai-shu/an-zhuang-ben-di-kai-fa-huan-jing/install.html
it is because go get can only download master branch of each dependency project,and some project changed APIs

**Comment by willxm** [comment]
thanks let me try
