### ISSUE TITLE
go-restful has removed SetCacheReadEntity

### ISSUE THREAD

**Issue by liwei5** [ServiceComb/go-chassis#50]
![image](https://user-images.githubusercontent.com/1586298/35651644-6f0d3560-071b-11e8-981c-a8dcd3295780.png)

### /server/restful/restful_server.go b/server/restful/restful_server.go   line:34

![image](https://user-images.githubusercontent.com/1586298/35651769-cf70435c-071b-11e8-911e-145ac42eb667.png)

**Comment by tianxiaoliang** [comment]
https://github.com/ServiceComb/go-chassis/issues/41 same issue

**Comment by tianxiaoliang** [comment]
plz refer to this issue,i will close this one
