### ISSUE TITLE
import cycle

### ISSUE THREAD

**Issue by lexkong** [ServiceComb/go-chassis#84]
github.com/ServiceComb/go-chassis/metrics **import:**  "github.com/ServiceComb/cse-collector"

"github.com/ServiceComb/cse-collector" **import:** github.com/ServiceComb/go-chassis/metrics

**Comment by tianxiaoliang** [comment]
will check this

**Comment by lexkong** [comment]
use this to build a microservice app

**Comment by tianxiaoliang** [comment]
I fixed, plz check again
