### ISSUE TITLE
how can i use go-chassis upload and download file?

### ISSUE THREAD

**Issue by andyzheung** [ServiceComb/go-chassis#85]
I want to use go-chassis to dev a micro-service, which can provide upload/download file by http, also my service is more than 2 instances, I also want to loadbalance fuction. If can provide a demo,how to achieve this function?

**Comment by tianxiaoliang** [comment]
https://github.com/ServiceComb/go-chassis/tree/master/examples/rest
we have a simple http example here, we expose native fasthttp request and response, so the answer to " upload/download file" is yes, you can.

**Comment by andyzheung** [comment]
You priver the example is too simple,that just tell me how to dev a rest interface.
func main() {
	chassis.RegisterSchema("rest", &schemas.RestFulHello{}, serverOption.WithSchemaID("RestHelloService"))
	if err := chassis.Init(); err != nil {
		lager.Logger.Error("Init failed.", err)
		return
	}
	chassis.Run()
}
I use http stream transport like this demo under, i don't know how to use that match to go-chassis and i also need to use client load balance:
====>simple demo,multipart file:
func uploadHandler(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	//POST takes the uploaded file(s) and saves it to disk.
	case "POST":
		//parse the multipart form in the request
		err := r.ParseMultipartForm(1024)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		//get a ref to the parsed multipart form
		m := r.MultipartForm

		//get the *fileheaders
		files := m.File["uploadfile"]
		for i, _ := range files {
			//for each fileheader, get a handle to the actual file
			file, err := files[i].Open()
			defer file.Close()
			if err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			//create destination file making sure the path is writeable.
			dst, err := os.Create("H:\\Project\\Go\\mygolearn\\file2\\" + files[i].Filename)

			fmt.Println("test.")

			defer dst.Close()
			if err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			//copy the uploaded file to the destination file
			if _, err := io.Copy(dst, file); err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}

		}

	default:
		w.WriteHeader(http.StatusMethodNotAllowed)
	}
}
or transfer file by http body like this:
func binaryuploadHandler(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	//POST takes the uploaded file(s) and saves it to disk.
	case "POST":
		var count int64 = 0
		var ntest int64 = 0
		defer r.Body.Close()
		buf := make([]byte, 1024)
		dst, err := os.Create("H:\\Project\\Go\\mygolearn\\file2\\test1.txt" )
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		for {
			n, err := r.Body.Read(buf)
			fmt.Printf("before n=%d,err=%v",n,err)
			if err != nil && err != io.EOF {
				fmt.Printf("error")
				return
			}
			dst.WriteAt(buf[:n],count)
			ntest = (int64)(n)
			count += ntest

			if err == io.EOF {
				fmt.Printf("break")
				break
			}

		}

	default:
		w.WriteHeader(http.StatusMethodNotAllowed)
	}
}

**Comment by tianxiaoliang** [comment]
here is example of native net/http
https://gist.github.com/ebraminio/576fdfdff425bf3335b51a191a65dbdb
and here is the fasthttp 
https://github.com/valyala/fasthttp
plz refert to 
**Switching from net/http** to fasthttp section in readme

and in go chassis
you can use req.GetRequest() to get native fasthttp request.

**Comment by tianxiaoliang** [comment]
in server side we support native net/http, 
you can use ctx.ReadRequest() to get http req
and I will also expose a API tp return you http resp

**Comment by tianxiaoliang** [comment]
and we will also write an example for this case
For now you can refer to my comment to reach this goal

**Comment by andyzheung** [comment]
thx. If i use go-chassis, also can help me solve multi instances load balance, right?

**Comment by joseph-v** [comment]
@andyzheung, an example implementation for multipart form upload using go-chassis and source code you provided here, is uploaded in location (https://github.com/joseph-v/go-chassis-upload-example). Please ensure PR (https://github.com/ServiceComb/go-chassis/pull/96) #96  is available in the go-chassis code for above example to work.

**Comment by tianxiaoliang** [comment]
close this issue, since example is supplied
